services:
  develop:
    build:
      context: .
      target: develop
      dockerfile: ./src/Dockerfile
    volumes:
      - .:/home/pleckjp
    working_dir: /home/pleckjp
    container_name: pleckjp-develop
    command:
      - /bin/bash
      - -c
      - |
        make -j$(nproc) with-fontforge
        make -j$(nproc) with-fontforge
  release:
    build:
      context: .
      target: release
      dockerfile: ./src/Dockerfile
    volumes:
      - ./build:/home/pleckjp/build
    container_name: pleckjp-release
